import type { Metadata } from "next";
import { Geist, Geist_Mono, JetBrains_Mono, Oxanium } from "next/font/google";
import "./globals.css";
import { Toaster } from "sonner";
import { cn } from "../lib/utils";
import { FloatingGhosts } from "../components/ui/floating-ghosts";

const oxaniumHeading = Oxanium({
  subsets: ["latin"],
  variable: "--font-heading",
});

const jetbrainsMono = JetBrains_Mono({
  subsets: ["latin"],
  variable: "--font-mono",
});

const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({ children }: LayoutProps<"/">) {
  return (
    <html
      lang="en"
      className={cn(
        "h-full",
        "antialiased",
        geistSans.variable,
        geistMono.variable,
        "font-mono",
        jetbrainsMono.variable,
        oxaniumHeading.variable,
      )}
    >
      <body className="min-h-full flex flex-col bg-zinc-950 text-zinc-100 relative selection:bg-purple-900 selection:text-purple-200">
        <div className="fixed inset-0 bg-[radial-gradient(ellipse_at_top,_var(--tw-gradient-stops))] from-purple-950/20 via-zinc-950 to-black pointer-events-none z-0" />

        <FloatingGhosts />

        <div className="relative z-10 flex-1 flex flex-col">{children}</div>

        <Toaster theme="dark" richColors />
      </body>
    </html>
  );
}
